# Uncomment the next line to define a global platform for your project
 platform :ios, '14.3'

target 'Cashably' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cashably
    pod 'Alamofire'
    # loading animation
    pod 'NVActivityIndicatorView/Extended'

    pod 'UITextField+Shake'

    pod 'FlagPhoneNumber'
    
    pod 'MKRingProgressView'
    pod 'Charts'

    pod 'Plaid'

    pod 'FirebaseAuth'
    pod 'FirebaseAnalytics'

  target 'CashablyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CashablyUITests' do
    # Pods for testing
  end

end
