# Uncomment the next line to define a global platform for your project
 platform :ios, '14.3'

target 'Cashably' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cashably
    pod 'Alamofire'
    # loading animation
    pod 'NVActivityIndicatorView/Extended'
    pod 'JGProgressHUD'

    pod 'UITextField+Shake'
    pod 'iOSDropDown'
    pod 'FlagPhoneNumber'
    pod 'MBCheckboxButton'
    pod 'MBRadioButton'
#    pod 'SVPinView', '~> 1.0'
    pod 'DPOTPView'
    pod 'FittedSheets'
    
    pod 'MKRingProgressView'
    pod 'Charts', '~>3.6.0'
    pod 'MKMagneticProgress'
    
    pod 'IQKeyboardManagerSwift'

    pod 'Plaid'

    pod 'FirebaseAuth', '~>9.0'
    pod 'FirebaseAnalytics', '~>9.0'
    pod 'FirebaseFirestore', '~>9.0'
    pod 'FirebaseStorage'

  target 'CashablyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CashablyUITests' do
    # Pods for testing
  end

end
